[workspace]
resolver = "2"
members = ["crates/bevy_hui", "crates/bevy_hui_widgets", "example"]
default-members = ["crates/bevy_hui"]

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
